### ISSUE TITLE
[Tracking] w3up phase 2

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/w3protocol#220]
# Phase 2 

**Summary**

Phase 2 will run until Friday February 3rd and has been broken down by priority: 
🔴 P0
🟡 P1
🟢 P2

**What success looks like for this phase:**

1) Provider and account system so users can log into the website, recover passwords, etc.

2) Log system to be able to track usage, implement metrics

3) w3ui and w3console so users can in use a web console with w3up

-------------

# 🔴  P0

## metrics and logs
- [ ] examine kinesis logs @jchris @vasco-santos 
- [ ] get w3access to feed into kinesis 

- [ ] [Unify UCAN API endpoints](https://github.com/web3-storage/w3protocol/issues/325) @gobengo @Gozala 

## w3infra integration tests

Team: 
@vasco-santos (primary)
@hugomrdias (support)

**Motivation:** guarantee no regressions exist when independent systems are updated https://github.com/web3-storage/w3infra/issues/9

- [x] Decide on setup for integration tests https://github.com/web3-storage/w3infra/pull/122

https://github.com/web3-storage/w3infra/issues/9: 
- [x] Test `store/*` and `upload/*` flows with w3up-client + using access 
  - [x] Test DUDEWHERE
- [x] Test flows on CARPARK write event
  - [x] Car replicated
  - [x] Side Index created + replicated

 ^also tracked by this ticket from Phase 1 https://github.com/web3-storage/w3protocol/issues/152

## implement receipts
Team: @Gozala @gobengo 

**Motivation**: Accurate accounting e.g. generate a receipt for upload received

- [ ] https://github.com/web3-storage/ucanto/issues/151
- [ ] align with [spec](https://github.com/ucan-wg/invocation/) ([draft](https://github.com/ucan-wg/invocation/blob/rough/README.md))
- [ ] https://github.com/ucan-wg/spec/issues/139
- [ ] https://github.com/ucan-wg/invocation/issues/6
- [ ] [allow receipt for uploaded CAR ](https://github.com/web3-storage/w3infra/issues/95)
- [ ] Websocket(?) API to subscribe to “status receipts” (tracking an upload through the system)

## implement [spec for providers ](https://github.com/web3-storage/specs/blob/main/w3-space.md) (⛰ epic)
Team: @hugomrdias @vasco-santos @gobengo 

### Tasks

- [ ] #347
    - [ ]  validation phrase should be printed in the agent requesting the email flow
- [x] #348
- [ ] #293 
- [ ] #341
- [ ] #349
- [ ] #350
- [ ] #371

## implement [spec for accounts ](https://github.com/web3-storage/specs/blob/main/w3-account.md) (⛰ epic)
Team: @hugomrdias @gobengo @alanshaw 

**Motivation:** cross application key sharing & verification once per agent not once per space

### Tasks

- [ ] #384
- [x] #385
- [x] #386
- [ ] #393
- [ ] #394
- [ ] #395

## create keyring site (⛰ epic) (DESCOPED)
Team: @olizilla @travis @alanshaw @hugomrdias 

[Requirements for MVP](https://www.notion.so/w3keyring-principles-7cf67adf3aab4f4fa01dd0410793ab73)

- [ ] with w3ui

## w3console (⛰ epic)

Team: @travis @olizilla @yusefnapora 

**w3ui**
- [x] testing https://github.com/web3-storage/w3ui/issues/150
  - [x] https://github.com/web3-storage/w3ui/issues/223
  - [x] https://github.com/web3-storage/w3ui/issues/222
- [ ] ship `HeadlessUI` & CustomizableUI for React
  - [x] headless https://github.com/web3-storage/w3ui/pull/136
  - [x] customizable https://github.com/web3-storage/w3ui/pull/208
    - [x] https://github.com/web3-storage/w3ui/issues/235
- [ ] integrate keyring site into `keyring-core`  (⚠️ dependency on accounts spec work) https://github.com/web3-storage/w3ui/issues/226

**w3console**

**Motivation:** to get beta w3console shipped

**Reference docs:**
[user stories](https://www.notion.so/Sign-in-flows-139c97bd826b491dbd1d9f5acaa7de3f)
[diagram](https://github.com/web3-storage/w3protocol/blob/main/spec/sequences/registration.md)
[product meeting](https://www.notion.so/2023-01-11-w3console-sync-61fddb8e32394271a8aa0c529720d7de)
[product requirements](https://www.notion.so/CSS-variable-design-system-35a95134d43a45f9a9fb0a160bb9fb6c)

- [ ] https://github.com/web3-storage/w3ui/issues/120 @travis 
- [ ] design work for console site
   - [ ] user flows for console @jchris 
   - [ ] https://github.com/web3-storage/w3ui/issues/134 @cmunns 
   - [ ] when https://github.com/web3-storage/w3ui/issues/120 is complete, @cmunns can begin work on the layout/design
- [ ] build MVP using w3ui
   - [ ] Space explorer
     - [x] https://github.com/web3-storage/w3ui/issues/227
     - [x] https://github.com/web3-storage/w3ui/issues/230
   - [ ] DnD uploader (requirement: always visible)
     - [x] https://github.com/web3-storage/w3ui/issues/228
     - [x] https://github.com/web3-storage/w3ui/issues/231
   - [ ] Paginated uploads list
     - [x] https://github.com/web3-storage/w3ui/issues/229
     - [x] https://github.com/web3-storage/w3ui/issues/232
   - [ ] Bucket UI (?)
     - [ ] https://github.com/web3-storage/w3ui/issues/233
   - [ ] Keyring site integration
     - [ ] https://github.com/web3-storage/w3ui/issues/226
     - [ ] https://github.com/web3-storage/w3ui/issues/234
- [ ] ship to `beta.console.web3.storage`
- [ ] update existing website to guide users to new console (end of Phase 2/start of Phase 3)

## Getting off IPFS Cluster

Team: @blucas @olizilla @alanshaw

**Motivation:** cost saving, scalability, be in charge of our own infra

Proposal: https://hackmd.io/@olizilla/Bk-NMVQ9o

- [ ] Rollout Pickup https://github.com/web3-storage/backup/issues/1
- [ ] Migrate data from IPFS Cluster to S3 buckets https://github.com/web3-storage/backup/issues/1

## Filecoin pipeline: CAR aggregator for space 

Team: @vasco-santos @Gozala @alanshaw 

- [x] Align on proposal https://hackmd.io/@vasco-santos/BJ_-zDVqj
- [x] `w3filecoin` scafold 
- [x] `w3filecoin` Data stack https://github.com/web3-storage/w3filecoin/pull/9
- [ ] `commP` support in client https://github.com/web3-storage/w3protocol/issues/353
- [ ] `w3filecoin` Consumer Stack
- [ ] `w3filecoin` integrate with Spade

## checkup 

- [ ] update checkup bucket for nft/web3 @blucas @alanshaw @gobengo 
   **Motivation**: new CIDs are not being checked
   - [ ] Add support of multiple buckets

### P0
- [x] blog updates reflecting changes to w3up here: https://github.com/web3-storage/web3.storage/issues/2184 @yusefnapora 
- [x] Capabilities package READMEs
- [x] [quick start guide](https://github.com/web3-storage/web3.storage/issues/2190) @yusefnapora 
- [x] new docs website https://github.com/web3-storage/web3.storage/issues/2190
- [ ] update technical docs so that users can pickup and use our kit
- [ ] add account recovery to access-client and w3up-client (note: we should focus on w3up-client, less access since that is where folks should go) [@yusefnapora](https://github.com/yusefnapora)
- [ ] spec for store / upload 
           https://github.com/web3-storage/w3protocol/issues/326
           https://github.com/web3-storage/specs/issues/40

### P1
- [ ] figure out how to layer in user owned / app owned spaces
- [ ] headless UI docs  @yusefnapora 
  - [ ] add components to markdown docs: https://github.com/web3-storage/w3ui/pull/241
  - [ ] update react examples to use headless components
  - [ ] update react examples on w3ui website
 - [ ] flowchart draft for docs site. Structure based on user stories (different sections/flows based on needs)
- [ ] different user guides with user-friendly language 

# 🟡 P1

## w3console

Team: @travis @olizilla @yusefnapora 

**w3ui**
- [x] add `HeadlessUI` for Vue & Solid (adaptation of React base in #136) 
- [x] add `CustomizableUI` for Vue & Solid (adaptation of React base in #136)
- [ ] add overview of `HeadlessUI` & `CustomizableUI` to [w3ui website](https://beta.ui.web3.storage/)

##

- [ ] publicly verifiable timestamps for UCAN invocations @alanshaw @Gozala @hugomrdias 
   Motivation: https://github.com/web3-storage/specs/pull/27

- [ ] https://github.com/web3-storage/w3up-client/issues/54 and https://github.com/ipld/js-unixfs/issues/37 @Gozala @alanshaw @gobengo 
   Motivation: support for 10k NFT drops

- [ ] CAR retrieval by CAR CID @gobengo @Gozala
   https://github.com/web3-storage/w3protocol/issues/274
   Motivation: verifiable downloads ✅ 

- [ ] UCAN log stream consumer for billing @vasco-santos @hugomrdias @gobengo @Gozala 
   (last piece of billing work before Stripe integration can begin)

# 🟢 P2

- [ ] UCAN log stream consumers @vasco-santos @Gozala
      - Metrics wanted https://github.com/web3-storage/w3infra/issues/117
      - Queryable DB

- [ ] UCAN S3 log issue @vasco-santos @alanshaw 
      - Multiple invocations for the same UCAN has write freq limitations

- [ ] ability to easily delegate a subset of perms to a UCAN

- [ ] https://github.com/web3-storage/w3protocol/issues/167
    - make NFT . Storage consumer of new services
    - make using w3ui
    - setup consumer
    - backup to NFT. Storage feature

# 🏁 DONE 🏁 

Phase 3 tickets:
https://github.com/web3-storage/w3protocol/issues/353
