### ISSUE TITLE
Implement `access/delegate` in `access-api`

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/w3protocol#393]
https://github.com/web3-storage/specs/blob/main/w3-access.md#accessdelegate

* [x] https://github.com/web3-storage/specs/issues/45
* [x] #414
* [x] space registration (because access/delegate checks for this) https://github.com/web3-storage/w3protocol/issues/459
* [x] https://github.com/web3-storage/w3protocol/pull/483
* [x] #425 access-api access/delegate handler stores nb.delegations so that they can be claimed by access/claim
  * unblocks https://github.com/web3-storage/w3protocol/issues/394
  * [x] https://github.com/web3-storage/w3protocol/issues/464 - discovered while tesitng in staging
* [x] demo `access/delegate` in observable against staging https://observablehq.com/d/95bfec64fbb3c2d1

**Comment by gobengo** [comment]
#status need review on https://github.com/web3-storage/w3protocol/pull/420

**Comment by gobengo** [comment]
@alanshaw fyi I just updated the OP link to the spec from a `feat/` branch to the main branch link

old: https://github.com/web3-storage/specs/blob/feat/w3-authorization/w3-access.md#accessdelegate
new: https://github.com/web3-storage/specs/blob/main/w3-access.md#accessdelegate

**Comment by gobengo** [comment]
#status see https://github.com/web3-storage/w3protocol/issues/425#issuecomment-1426055978

**Comment by gobengo** [comment]
#status I can't show off `access/delegate` working e2e until we have a way of registering a space, which we're implementing as https://github.com/web3-storage/w3protocol/issues/459

**Comment by gobengo** [comment]
this is done in access-api trunk, and `@web3-storage/access` (access-client) makes use of it as of https://github.com/web3-storage/w3protocol/issues/395
